64 mark book as out of stock
smruti-banty/library-management pull request #69
Opened 2023-10-29 06:32 UTC by manas-chandan

- [x] define method for out of stock book
- [x] implemented method for out of stock book
- [x] controller method for out of stock book add

2023-10-29 12:50 UTC, smruti-banty commented on backend/src/main/java/com/lms/backend/services/impl/BookServiceImpl.java
set updated date

2023-10-29 12:51 UTC, smruti-banty requested changes
Change accordingly

2023-10-30 08:47 UTC, manas-chandan commented
changes done accordingly.

2023-10-30 13:23 UTC, smruti-banty approved these changes
LGTM.

2023-10-30 13:23 UTC, merged